on:
  release:
    types:
      - created
jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: ./scripts/build.sh
      
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: zlib-package
          path: dist/package/zlib/
          if-no-files-found: error
      
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: zlib-package
          path: dist/
      - run: cd dist; zip -r ../zlib-package.zip .
      - run:
          gh release upload ${{ github.event.release.tag_name }}
          zlib-package.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}